apiVersion: apps/v1
kind: Deployment
metadata:
  name: authmsdpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuthMicroService
  template:
    metadata:
      labels:
        app: AuthMicroService
    spec:
      containers:
      - name: msregistry
        image: msregistry.azurecr.io/msregistry:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn
---
apiVersion: v1
kind: Service
metadata:
  name: authmsservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: AuthMicroService